version: "3.9"

services:
  ui:
    image: ecommerce-login-ui
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_IDENTITY_SERVICE_BASE_URL=http://localhost:1000
    container_name: ecommerce-login-ui
    ports:
      - 2000:80
    restart: on-failure
